pub mod academic;
pub mod admission;
pub mod attendance;
pub mod audit;
pub mod communication;
pub mod event_bus;
pub mod finance;
pub mod grades;
pub mod hr;
pub mod modules;
pub mod reporting;
pub mod roles;
pub mod rut;
pub mod school;
pub mod student;
pub mod user;

#[cfg(feature = "db")]
pub mod db_schema;
